apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: oci://quay.io/jetstack/charts/cert-manager
      path: .
      targetRevision: v1.19.1
      helm:
        releaseName: cert-manager
        valueFiles:
          - '$repo/apps/00-operators/cert-manager/values.yaml'
    - repoURL: https://github.com/kuanchoulai10/argocd-demo
      targetRevision: main
      ref: repo
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true