apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: oci://public.ecr.aws/karpenter/karpenter
      path: .
      targetRevision: 1.8.1
      helm:
        releaseName: karpenter
        valuesObject:
          settings:
            clusterName: test
  destination:
    name: in-cluster
    namespace: karpenter
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true