apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: 'default'
  sources:
    - repoURL: https://strimzi.io/charts/
      chart: strimzi-operator
      targetRevision: 2.3.0
      helm:
        releaseName: strimzi-operator
        valueFiles:
          - '$repo/apps/00-operators/strimzi/values.yaml'
    - repoURL: https://github.com/kuanchoulai10/argocd-demo
      targetRevision: main
      ref: repo
  destination:
    name: in-cluster
    namespace: strimzi-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true