apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-apps
  namespace: argocd
spec:
  project: 'default'
  sources:
    - repoURL: https://github.com/kuanchoulai10/argocd-demo
      targetRevision: main
      path: app-of-apps
      directory:
        recurse: true
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true